{% set version = "1.0-21" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sf/sf_{{ version }}.tar.gz
  sha256: 70c28a826387a56b5f270d48cbb42999f6fb59ec0e6984c84df920dbe0206e99
  patches:
    - patches/0001-minimal-ucrt-libs.patch

build:
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/Rblas.dll'       # [win]
    - '*/Rlapack.dll'     # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  skip: True              # [ppc64le]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-classint                   # [build_platform != target_platform]
    - r-dbi                        # [build_platform != target_platform]
    - r-magrittr                   # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-s2                         # [build_platform != target_platform]
    - r-units                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('r_clang') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-classint >=0.4_1
    - r-dbi >=0.8
    - r-magrittr
    - r-rcpp >=0.12.18
    - r-s2 >=1.1.0
    - r-units >=0.7_0
    - geos
    - libgdal-core
    - proj
  run:
    - r-base
    - r-classint >=0.4_1
    - r-dbi >=0.8
    - r-magrittr
    - r-rcpp >=0.12.18
    - r-s2 >=1.1.0
    - r-units >=0.7_0

test:
  commands:
    - $R -e "library('sf')"           # [not win]
    - "\"%R%\" -e \"library('sf')\""  # [win]

about:
  home: https://r-spatial.github.io/sf/
  dev_url: https://github.com/r-spatial/sf/
  license: GPL-2.0-only OR MIT
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and to 'PROJ' for projection conversions and datum transformations.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
